name: lavenderleit.dev

services:
  lavenderleit.dev:
    image: lavenderleit.dev:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: .env
    container_name: lavenderleit.dev
